# Generated by Django 5.0.6 on 2024-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, max_length=250)),
                (
                    "image",
                    models.ImageField(
                        default="default_course_image.png",
                        upload_to="courses/%Y/%m/%d/",
                    ),
                ),
                ("facebook", models.URLField(blank=True, max_length=100)),
                ("twitter", models.URLField(blank=True, max_length=100)),
                ("linkedin", models.URLField(blank=True, max_length=100)),
                ("youtube", models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
