# Generated by Django 5.0.6 on 2024-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (   
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Kurs Adini Yaziniz",
                        max_length=50,
                        unique=True,
                        verbose_name="Kurs Adi",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        default="courses/default_course_image.jpg",
                        upload_to="courses/%Y/%m/%d/",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("avaialable", models.BooleanField(default=True)),
            ],
        ),
    ]
