# Generated by Django 5.0.6 on 2024-06-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="avaialable",
            new_name="available",
        ),
    ]
