# Generated by Django 5.0.6 on 2024-06-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="tags",
            new_name="tag",
        ),
    ]
