# Generated by Django 5.0.6 on 2024-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_rename_tags_course_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                default="default_course_image.png", upload_to="courses/%Y/%m/%d/"
            ),
        ),
    ]
